# Generated by Django 3.2.4 on 2021-06-12 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_auto_20210612_0217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classroom',
            old_name='class_code',
            new_name='class_codes',
        ),
    ]
