# Generated by Django 3.2.4 on 2021-06-13 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classes', '0004_rename_class_code_classroom_class_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='facultyiD',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
