# Generated by Django 3.1.7 on 2021-06-14 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210501_1601'),
        ('classes', '0005_alter_classroom_facultyid'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='course_section',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='facultyiD',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.faculty'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
