# Generated by Django 3.1.7 on 2021-06-14 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_auto_20210614_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='class_code',
            field=models.CharField(blank=True, default=None, max_length=6, null=True, unique=True),
        ),
    ]
