# Generated by Django 3.1.7 on 2021-07-27 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0017_auto_20210727_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_submission',
            name='student_post_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
