# Generated by Django 3.1.7 on 2021-03-30 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyprofile',
            name='department',
            field=models.CharField(choices=[('Accounting & Finance', 'Accounting & Finance'), ('Economics', 'Economics'), ('Management', 'Management'), ('Marketing & International Business', 'Marketing & International Business'), ('MBA & EMBA Programs', 'MBA & EMBA Programs'), ('Architecture', 'Architecture'), ('Civil & Environmental Engineering', 'Civil & Environmental Engineering'), ('Electrical & Computer Engineering', 'Electrical & Computer Engineering'), ('Mathematics & Physics', 'Mathematics & Physics'), ('English & Modern Languages', 'English & Modern Languages'), ('Political Science & Sociology', 'Political Science & Sociology'), ('Law', 'Law'), ('Biochemistry & Microbiology', 'Biochemistry & Microbiology'), ('Environmental Science & Management', 'Environmental Science & Management'), ('Pharmaceutical Sciences', 'Pharmaceutical Sciences'), ('Public Health', 'Public Health')], default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='department',
            field=models.CharField(choices=[('Accounting & Finance', 'Accounting & Finance'), ('Economics', 'Economics'), ('Management', 'Management'), ('Marketing & International Business', 'Marketing & International Business'), ('MBA & EMBA Programs', 'MBA & EMBA Programs'), ('Architecture', 'Architecture'), ('Civil & Environmental Engineering', 'Civil & Environmental Engineering'), ('Electrical & Computer Engineering', 'Electrical & Computer Engineering'), ('Mathematics & Physics', 'Mathematics & Physics'), ('English & Modern Languages', 'English & Modern Languages'), ('Political Science & Sociology', 'Political Science & Sociology'), ('Law', 'Law'), ('Biochemistry & Microbiology', 'Biochemistry & Microbiology'), ('Environmental Science & Management', 'Environmental Science & Management'), ('Pharmaceutical Sciences', 'Pharmaceutical Sciences'), ('Public Health', 'Public Health')], default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='facultyprofile',
            name='bio',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='facultyprofile',
            name='facultyID',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
