# Generated by Django 3.1.7 on 2021-04-16 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_auto_20210401_0132'),
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Accounting & Finance', 'Accounting & Finance'), ('Economics', 'Economics'), ('Management', 'Management'), ('Marketing & International Business', 'Marketing & International Business'), ('MBA & EMBA Programs', 'MBA & EMBA Programs'), ('Architecture', 'Architecture'), ('Civil & Environmental Engineering', 'Civil & Environmental Engineering'), ('Electrical & Computer Engineering', 'Electrical & Computer Engineering'), ('Mathematics & Physics', 'Mathematics & Physics'), ('English & Modern Languages', 'English & Modern Languages'), ('Political Science & Sociology', 'Political Science & Sociology'), ('Law', 'Law'), ('Biochemistry & Microbiology', 'Biochemistry & Microbiology'), ('Environmental Science & Management', 'Environmental Science & Management'), ('Pharmaceutical Sciences', 'Pharmaceutical Sciences'), ('Public Health', 'Public Health')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('facultyID', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('initials', models.CharField(max_length=10)),
                ('bio', models.CharField(max_length=500)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.department')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('studentID', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.department')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='FacultyProfile',
        ),
        migrations.DeleteModel(
            name='StudentProfile',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
